server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    url: xxx
    username: xxx
    password: xxx
    driver-class-name: xxxx
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.example.menu.entity
